export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PREPARING = 'PREPARING',
  READY_FOR_SHIPMENT = 'READY_FOR_SHIPMENT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
