export const categories = [
  {
    name: 'Pizza',
    slug: 'pizza',
    description: 'Delicious pizzas with various toppings',
    isActive: 1,
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Combo',
    slug: 'combo',
    description: 'Value meal combos',
    isActive: 1,
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Khai vị',
    slug: 'khai-vi',
    description: 'Appetizers and starters',
    isActive: 1,
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Đồ uống',
    slug: 'do-uong',
    description: 'Refreshing beverages',
    isActive: 1,
    sortOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cà phê',
    slug: 'ca-phe',
    description: 'Coffee drinks',
    isActive: 1,
    sortOrder: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mỳ Ý',
    slug: 'my-y',
    description: 'Italian pasta dishes',
    isActive: 1,
    sortOrder: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
