export const categories = [
  {
    name: 'Pizza',
    slug: 'pizza',
    description: 'Delicious pizzas with various toppings',
    isActive: 1,
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Combo',
    slug: 'combo',
    description: 'Value meal combos',
    isActive: 1,
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Khai vị',
    slug: 'khai-vi',
    description: 'Appetizers and starters',
    isActive: 1,
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Đồ uống',
    slug: 'do-uong',
    description: 'Refreshing beverages',
    isActive: 1,
    sortOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cà phê',
    slug: 'ca-phe',
    description: 'Coffee drinks',
    isActive: 1,
    sortOrder: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mỳ Ý',
    slug: 'my-y',
    description: 'Italian pasta dishes',
    isActive: 1,
    sortOrder: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const ingredients = [
  {
    name: 'Viền phô mai',
    description: 'Cheese-stuffed crust',
    price: 179000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/99f5cb91225b4875bd06a26d2e842106.png',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mozzarella kem',
    description: 'Creamy mozzarella cheese',
    price: 79000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/cdea869ef287426386ed634e6099a5ba.png',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Phô mai Cheddar',
    description: 'Sharp cheddar cheese',
    price: 79000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA69C1FE796',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Ớt Jalapeno cay',
    description: 'Spicy jalapeno peppers',
    price: 59000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/11ee95b6bfdf98fb88a113db92d7b3df.png',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Gà mềm',
    description: 'Tender chicken',
    price: 79000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A39D824A82E11E9AFA5B328D35A',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Nấm mỡ',
    description: 'Fresh mushrooms',
    price: 59000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA67259A324',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Giăm bông',
    description: 'Cured ham',
    price: 79000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A39D824A82E11E9AFA61B9A8D61',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Xúc xích Pepperoni cay',
    description: 'Spicy pepperoni sausage',
    price: 79000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA6258199C3',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Xúc xích Chorizo cay',
    description: 'Spicy chorizo sausage',
    price: 79000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA62D5D6027',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dưa chuột muối chua',
    description: 'Pickled cucumbers',
    price: 59000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A21DA51A81211E9EA89958D782B',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cà chua tươi',
    description: 'Fresh tomatoes',
    price: 59000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A39D824A82E11E9AFA7AC1A1D67',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Hành tây đỏ',
    description: 'Red onions',
    price: 59000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA60AE6464C',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dứa tươi',
    description: 'Fresh pineapple',
    price: 59000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A21DA51A81211E9AFA6795BA2A0',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Rau thơm Ý',
    description: 'Italian herbs',
    price: 39000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/370dac9ed21e4bffaf9bc2618d258734.png',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Ớt chuông ngọt',
    description: 'Sweet bell peppers',
    price: 59000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA63F774C1B',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Phô mai Feta viên',
    description: 'Feta cheese cubes',
    price: 79000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A39D824A82E11E9AFA6B0FFC349',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Thịt viên',
    description: 'Meatballs',
    price: 79000,
    imageUrl: 'https://cdn.dodostatic.net/static/Img/Ingredients/b2f3a5d5afe44516a93cfc0d2ee60088.png',
    isActive: 1,
    isRequired: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const products = [
  {
    name: 'Pizza Hải Sản Pesto',
    slug: 'pizza-hai-san-pesto',
    description: 'Pizza với hải sản tươi ngon và sốt Pesto đặc biệt',
    basePrice: 179000,
    salePrice: 149000,
    img: 'https://media.dodostatic.com/image/r:292x292/11ef93517b036e5ca67b43ca2ba0ef12.avif',
    isActive: 1,
    isFeatured: 1,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pizza Xúc Xích Ý (Pepperoni)',
    slug: 'pizza-pepperoni',
    description: 'Pizza với xúc xích Ý (Pepperoni) đậm đà',
    basePrice: 169000,
    salePrice: 139000,
    img: 'https://media.dodostatic.com/image/r:233x233/11ef9351d1f5c9e8be730e2e763cba07.avif',
    isActive: 1,
    isFeatured: 1,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pizza Half & Half',
    slug: 'pizza-half-half',
    description: 'Pizza kết hợp hai loại nhân khác nhau',
    basePrice: 189000,
    salePrice: null,
    img: 'https://media.dodostatic.com/image/r:233x233/11eec6d827adfd26a9e97561a6da72c7.avif',
    isActive: 1,
    isFeatured: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pizza Hải Sản Truyền Thống',
    slug: 'pizza-hai-san-truyen-thong',
    description: 'Pizza hải sản truyền thống với hương vị đặc trưng',
    basePrice: 319000,
    salePrice: 289000,
    img: 'https://media.dodostatic.com/image/r:233x233/11ef935194a894b3a481b3ef98075096.avif',
    isActive: 1,
    isFeatured: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pizza 4 Loại Thịt',
    slug: 'pizza-4-loai-thit',
    description: 'Pizza với 4 loại thịt hảo hạng',
    basePrice: 189000,
    salePrice: 159000,
    img: 'https://media.dodostatic.com/image/r:233x233/11ef93515fa332bda9b7b15cc0b8c873.avif',
    isActive: 1,
    isFeatured: 1,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pizza 4 Cheese',
    slug: 'pizza-4-cheese',
    description: 'Pizza với 4 loại phô mai đặc trưng',
    basePrice: 179000,
    salePrice: null,
    img: 'https://media.dodostatic.com/image/r:233x233/11ef93508e3efc748cfe7a1318d7e73c.avif',
    isActive: 1,
    isFeatured: 0,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Bánh mì kẹp giăm bông và phô mai',
    slug: 'banh-mi-giam-bong-pho-mai',
    description: 'Bánh mì kẹp giăm bông và phô mai thơm ngon',
    basePrice: 99000,
    salePrice: 79000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EE796FF0059B799A17F57A9E64C725.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mizza Gà Popcorn',
    slug: 'mizza-ga-popcorn',
    description: 'Mizza gà popcorn giòn rụm, độc đáo',
    basePrice: 109000,
    salePrice: 89000,
    img: 'https://media.dodostatic.com/image/r:233x233/11ef935898342902a80f69edfead7a32.avif',
    isActive: 1,
    isFeatured: 1,
    categoryId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Khoai tây nướng lò với sốt',
    slug: 'khoai-tay-nuong',
    description: 'Khoai tây nướng lò với sốt đặc biệt',
    basePrice: 69000,
    img: 'https://media.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA67259A324',
    isActive: 1,
    isFeatured: 0,
    categoryId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dodster',
    slug: 'dodster',
    description: 'Dodster - món ăn nhanh độc đáo của Dodo Pizza',
    basePrice: 89000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EE796F96D11392A2F6DD73599921B9.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dodster cay',
    slug: 'dodster-cay',
    description: 'Dodster cay nồng, dành cho người thích vị cay',
    basePrice: 89000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EE796FD3B594068F7A752DF8161D04.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sữa lắc chuối',
    slug: 'sua-lac-chuoi',
    description: 'Sữa lắc chuối ngọt ngào, mát lạnh',
    basePrice: 59000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EEE20B8772A72A9B60CFB20012C185.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sữa lắc táo caramen',
    slug: 'sua-lac-tao-caramen',
    description: 'Sữa lắc táo caramen thơm ngon, độc đáo',
    basePrice: 59000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EE79702E2A22E693D96133906FB1B8.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sữa lắc bánh quy Oreo',
    slug: 'sua-lac-oreo',
    description: 'Sữa lắc bánh quy Oreo, món khoái khẩu của nhiều người',
    basePrice: 59000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EE796FA1F50F8F8111A399E4C1A1E3.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sữa lắc truyền thống',
    slug: 'sua-lac-truyen-thong',
    description: 'Sữa lắc truyền thống, hương vị tuổi thơ',
    basePrice: 59000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EE796F93FB126693F96CB1D3E403FB.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cappuccino caramen',
    slug: 'cappuccino-caramen',
    description: 'Cappuccino caramen ấm áp, thơm lừng',
    basePrice: 49000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EE7D61AED6B6D4BFDAD4E58D76CF56.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Latte dừa',
    slug: 'latte-dua',
    description: 'Latte dừa béo ngậy, hương vị nhiệt đới',
    basePrice: 49000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EE7D61B19FA07090EE88B0ED347F42.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Americano',
    slug: 'americano',
    description: 'Americano đậm đà, cho ngày mới tỉnh táo',
    basePrice: 39000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EE7D61B044583596548A59078BBD33.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Latte',
    slug: 'latte',
    description: 'Latte truyền thống, êm dịu',
    basePrice: 49000,
    img: 'https://media.dodostatic.net/image/r:292x292/11EE7D61B0C26A3F85D97A78FEEE00AD.webp',
    isActive: 1,
    isFeatured: 0,
    categoryId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mì Ý Hải Sản Sốt Pesto',
    slug: 'mi-y-hai-san-pesto',
    description: 'Mì Ý hải sản sốt Pesto, hương vị Địa Trung Hải',
    basePrice: 129000,
    img: 'https://media.dodostatic.com/image/r:233x233/11ef935840297bab88e4aae1632cb9bd.avif',
    isActive: 1,
    isFeatured: 0,
    categoryId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mì Ý Sốt Bò Bằm Xúc Xích',
    slug: 'mi-y-sot-bo-bam',
    description: 'Mì Ý sốt bò bằm và xúc xích, đậm đà',
    basePrice: 129000,
    img: 'https://media.dodostatic.com/image/r:233x233/11ef93584c9054ef9b657f6145a806e4.avif',
    isActive: 1,
    isFeatured: 0,
    categoryId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const combos = [
  {
    name: 'Combo Mizza + Nước ngọt',
    slug: 'combo-mizza-nuoc-ngot',
    description: 'Combo Mizza kèm nước ngọt, lựa chọn hoàn hảo cho bữa ăn',
    basePrice: 350000,
    img: 'https://media.dodostatic.com/image/r:233x233/019362cecca7743f96e2907d17cc2e8e.avif',
    isActive: 1,
    isFeatured: 1,
    categoryId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Combo Mizza + Khai vị + Nước ngọt',
    slug: 'combo-mizza-khai-vi-nuoc-ngot',
    description: 'Combo Mizza, khai vị và nước ngọt, đầy đủ cho bữa tiệc',
    basePrice: 450000,
    img: 'https://media.dodostatic.com/image/r:233x233/019444bd2d7e71f0a454241811ed5c61.avif',
    isActive: 1,
    isFeatured: 1,
    categoryId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Combo 2 người Pizza 23cm + 2 Nước ngọt',
    slug: 'combo-2-nguoi-pizza',
    description: 'Combo dành cho 2 người với pizza cỡ vừa và nước ngọt',
    basePrice: 300000,
    img: 'https://media.dodostatic.com/image/r:233x233/0193635397bb7069b3200f614052436a.avif',
    isActive: 1,
    isFeatured: 1,
    categoryId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const productVariants = [
  {
    productId: 1,
    name: 'Nhỏ (20cm) Mỏng',
    size: '20cm',
    type: 'SMALL',
    modifiedPrice: 0,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 1,
    name: 'Lớn (30cm) Vừa',
    size: '30cm',
    type: 'MEDIUM',
    modifiedPrice: 50000,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 2,
    name: 'Nhỏ (20cm) Mỏng',
    size: '20cm',
    type: 'SMALL',
    modifiedPrice: 0,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 2,
    name: 'Lớn (30cm) Vừa',
    size: '30cm',
    type: 'MEDIUM',
    modifiedPrice: 50000,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 3,
    name: 'Vừa (25cm) Vừa',
    size: '25cm',
    type: 'MEDIUM',
    modifiedPrice: 0,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 3,
    name: 'Lớn (30cm) Mỏng',
    size: '30cm',
    type: 'SMALL',
    modifiedPrice: 50000,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 4,
    name: 'Lớn (30cm) Vừa',
    size: '30cm',
    type: 'MEDIUM',
    modifiedPrice: 0,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    name: 'Vừa (25cm) Vừa',
    size: '25cm',
    type: 'MEDIUM',
    modifiedPrice: 0,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    name: 'Lớn (30cm) Mỏng',
    size: '30cm',
    type: 'SMALL',
    modifiedPrice: 50000,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 6,
    name: 'Vừa (25cm) Mỏng',
    size: '25cm',
    type: 'SMALL',
    modifiedPrice: 0,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 6,
    name: 'Lớn (30cm) Vừa',
    size: '30cm',
    type: 'MEDIUM',
    modifiedPrice: 50000,
    isActive: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example ProductIngredients (assuming some default ingredients for products)
export const productIngredients = [
  {
    productId: 1,
    ingredientId: 1,
    isDefault: 1,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 1,
    ingredientId: 2,
    isDefault: 1,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 2,
    ingredientId: 8,
    isDefault: 1,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    ingredientId: 7,
    isDefault: 1,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    ingredientId: 8,
    isDefault: 1,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    ingredientId: 9,
    isDefault: 1,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    ingredientId: 17,
    isDefault: 1,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 6,
    ingredientId: 2,
    isDefault: 1,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 6,
    ingredientId: 3,
    isDefault: 1,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 6,
    ingredientId: 16,
    isDefault: 1,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example Users
export const users = [
  {
    email: 'admin@fastfood.com',
    name: 'Admin FastFood',
    phone: '0901112233',
    role: 'admin',
    provider: 'local',
  },
  {
    email: 'customer@fastfood.com',
    name: 'Khách Hàng Thân Thiết',
    phone: '0902223344',
    role: 'customer',
    provider: 'local',
  },
  {
    email: 'customer1@example.com',
    name: 'Nguyễn Văn Khách',
    phone: '0903334455',
    role: 'customer',
    provider: 'local',
  },
];

// Example Addresses
export const addresses = [
  {
    street: '123 Đường Nguyễn Huệ',
    city: 'Hồ Chí Minh',
    district: 'Quận 1',
    ward: 'Bến Nghé',
    latitude: 10.7769,
    longitude: 106.7009,
    isDefault: 1,
  },
];

// Seed Coupons
export const coupons = [
  // 1. Mã giảm giá áp dụng chung (Public Deals)
  {
    code: 'FASTFOOD20',
    name: 'Giảm 20.000đ đơn từ 100k',
    description: 'Giảm ngay 20.000đ cho đơn hàng có giá trị từ 100.000đ',
    value: 20000,
    minOrderAmount: 100000,
    maxUser: 500,
    currentUses: 0,
    startDate: new Date('2026-01-01T00:00:00Z'),
    endDate: new Date('2027-12-31T23:59:59Z'),
    isActive: 1,
  },
  {
    code: 'WELCOME50',
    name: 'Ưu đãi chào bạn mới 50.000đ',
    description: 'Giảm 50.000đ cho đơn hàng đầu tiên từ 150.000đ',
    value: 50000,
    minOrderAmount: 150000,
    maxUser: 200,
    currentUses: 0,
    startDate: new Date('2026-01-01T00:00:00Z'),
    endDate: new Date('2027-12-31T23:59:59Z'),
    isActive: 1,
  },
  {
    code: 'FREESHIP15',
    name: 'Miễn phí vận chuyển 15.000đ',
    description: 'Hỗ trợ 15.000đ phí vận chuyển cho đơn từ 80.000đ',
    value: 15000,
    minOrderAmount: 80000,
    maxUser: 1000,
    currentUses: 0,
    startDate: new Date('2026-01-01T00:00:00Z'),
    endDate: new Date('2027-12-31T23:59:59Z'),
    isActive: 1,
  },
  {
    code: 'PIZZADAY30',
    name: 'Ngày hội Pizza giảm 30.000đ',
    description: 'Giảm 30.000đ cho tất cả đơn hàng từ 120.000đ',
    value: 30000,
    minOrderAmount: 120000,
    maxUser: 300,
    currentUses: 0,
    startDate: new Date('2026-01-01T00:00:00Z'),
    endDate: new Date('2027-12-31T23:59:59Z'),
    isActive: 1,
  },
  {
    code: 'PARTYDEAL100',
    name: 'Tiệc tùng linh đình giảm 100.000đ',
    description: 'Giảm 100.000đ cho đơn tiệc đông người từ 350.000đ',
    value: 100000,
    minOrderAmount: 350000,
    maxUser: 100,
    currentUses: 0,
    startDate: new Date('2026-01-01T00:00:00Z'),
    endDate: new Date('2027-12-31T23:59:59Z'),
    isActive: 1,
  },
  {
    code: 'FLASHDEAL10',
    name: 'Flash Sale giảm 10.000đ',
    description: 'Giảm ngay 10.000đ không giới hạn giá trị đơn tối thiểu',
    value: 10000,
    minOrderAmount: 0,
    maxUser: 1000,
    currentUses: 0,
    startDate: new Date('2026-01-01T00:00:00Z'),
    endDate: new Date('2027-12-31T23:59:59Z'),
    isActive: 1,
  },

  // 2. Mã giảm giá độc quyền dành riêng cho từng User (Personalized / Exclusive)
  {
    code: 'VIP_MEMBER50',
    name: 'Mã độc quyền VIP Member 50.000đ',
    description: 'Mã ưu đãi đặc quyền dành riêng cho khách hàng VIP thân thiết',
    value: 50000,
    minOrderAmount: 100000,
    maxUser: 100,
    currentUses: 0,
    startDate: new Date('2026-01-01T00:00:00Z'),
    endDate: new Date('2027-12-31T23:59:59Z'),
    isActive: 1,
  },
  {
    code: 'BIRTHDAY_GIFT100',
    name: 'Quà tặng sinh nhật thành viên 100.000đ',
    description: 'Chúc mừng sinh nhật! Tặng bạn voucher 100.000đ cho đơn từ 200.000đ',
    value: 100000,
    minOrderAmount: 200000,
    maxUser: 50,
    currentUses: 0,
    startDate: new Date('2026-01-01T00:00:00Z'),
    endDate: new Date('2027-12-31T23:59:59Z'),
    isActive: 1,
  },
  {
    code: 'COMEBACK_30K',
    name: 'Ưu đãi nhớ bạn quay lại 30.000đ',
    description: 'Ưu đãi dành riêng cho bạn khi quay trở lại đặt hàng tại FastFood',
    value: 30000,
    minOrderAmount: 100000,
    maxUser: 50,
    currentUses: 0,
    startDate: new Date('2026-01-01T00:00:00Z'),
    endDate: new Date('2027-12-31T23:59:59Z'),
    isActive: 1,
  },
  {
    code: 'SPECIAL_LOYALTY25',
    name: 'Tri ân khách hàng thân thiết 25.000đ',
    description: 'Mã giảm giá đặc biệt gửi tặng khách hàng gắn bó',
    value: 25000,
    minOrderAmount: 80000,
    maxUser: 50,
    currentUses: 0,
    startDate: new Date('2026-01-01T00:00:00Z'),
    endDate: new Date('2027-12-31T23:59:59Z'),
    isActive: 1,
  },
];

// Seed UserCoupons (Gán mã giảm giá độc quyền cho từng User)
export const userCoupons = [
  {
    userEmail: 'customer@fastfood.com',
    couponCode: 'VIP_MEMBER50',
    isUsed: 0,
    userdAt: null,
  },
  {
    userEmail: 'customer@fastfood.com',
    couponCode: 'BIRTHDAY_GIFT100',
    isUsed: 0,
    userdAt: null,
  },
  {
    userEmail: 'customer@fastfood.com',
    couponCode: 'SPECIAL_LOYALTY25',
    isUsed: 0,
    userdAt: null,
  },
  {
    userEmail: 'customer1@example.com',
    couponCode: 'VIP_MEMBER50',
    isUsed: 0,
    userdAt: null,
  },
  {
    userEmail: 'customer1@example.com',
    couponCode: 'COMEBACK_30K',
    isUsed: 0,
    userdAt: null,
  },
  {
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    couponCode: 'VIP_MEMBER50',
    isUsed: 0,
    userdAt: null,
  },
  {
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    couponCode: 'BIRTHDAY_GIFT100',
    isUsed: 0,
    userdAt: null,
  },
  {
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    couponCode: 'SPECIAL_LOYALTY25',
    isUsed: 0,
    userdAt: null,
  },
];

// Seed Notifications for User 25aed8f1-6609-4720-8f09-f3d0f1256b6b
export const notifications = [
  {
    userId: '25aed8f1-6609-4720-8f09-f3d0f1256b6b',
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    title: 'Đơn hàng #FF-510342-7968 đã được xác nhận! 🍕',
    content: 'Đơn hàng của bạn đã được tiếp nhận và nhà bếp đang bắt đầu chuẩn bị món ăn nóng hổi.',
    type: 'ORDER_STATUS',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
  },
  {
    userId: '25aed8f1-6609-4720-8f09-f3d0f1256b6b',
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    title: 'Tặng bạn Voucher 50.000đ VIP Member 🎉',
    content: 'Chúc mừng bạn đã nhận được mã ưu đãi VIP_MEMBER50 giảm ngay 50.000đ cho đơn hàng từ 100.000đ.',
    type: 'PROMOTION',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    userId: '25aed8f1-6609-4720-8f09-f3d0f1256b6b',
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    title: 'Freeship 15.000đ hôm nay 🛵',
    content: 'Áp dụng mã FREESHIP15 để được miễn phí vận chuyển cho tất cả đơn hàng từ 80.000đ.',
    type: 'PROMOTION',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    userId: '25aed8f1-6609-4720-8f09-f3d0f1256b6b',
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    title: 'Đơn hàng #FF-219401-4491 giao thành công ✅',
    content: 'Đơn hàng Pizza Hải Sản Pesto đã được giao thành công. Chúc bạn có một bữa ăn ngon miệng!',
    type: 'ORDER_STATUS',
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
  {
    userId: '25aed8f1-6609-4720-8f09-f3d0f1256b6b',
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    title: 'Chào mừng bạn đến với FastFood! 👋',
    content: 'Cảm ơn bạn đã đồng hành cùng FastFood. Hãy khám phá thực đơn đa dạng và nhận nhiều ưu đãi hấp dẫn nhé!',
    type: 'SYSTEM',
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
  },
];

// Seed Orders for User 25aed8f1-6609-4720-8f09-f3d0f1256b6b
export const seedOrders = [
  {
    orderNumber: 'FF-510342-7968',
    status: 'PREPARING',
    paymentStatus: 'PAID',
    paymentMethod: 'ONLINE',
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    guestName: 'Nguyễn Văn Kiên',
    guestPhone: '0987654321',
    guestAddress: 'Số 12 ngõ 58 Trương Định, Tương Mai, Hoàng Mai, Hà Nội',
    notes: 'Giao trước 12h trưa giúp mình, cảm ơn shop',
    deliveryFee: 15000,
    discount: 50000,
    createdAt: new Date(Date.now() - 1000 * 60 * 15), // 15 phút trước
    items: [
      {
        productName: 'Pizza Hải Sản Pesto',
        variantName: 'Size Lớn 30cm',
        ingredientNames: ['Viền phô mai', 'Mozzarella kem'],
        quantity: 1,
      },
      {
        productName: 'Sữa lắc bánh quy Oreo',
        quantity: 2,
      },
    ],
  },
  {
    orderNumber: 'FF-782103-9145',
    status: 'READY_FOR_SHIPMENT',
    paymentStatus: 'PENDING',
    paymentMethod: 'COD',
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    guestName: 'Nguyễn Văn Kiên',
    guestPhone: '0987654321',
    guestAddress: 'Tòa nhà FPT, Phố Duy Tân, Cầu Giấy, Hà Nội',
    notes: 'Gọi trước khi đến 5 phút nhé tài xế',
    deliveryFee: 15000,
    discount: 15000,
    createdAt: new Date(Date.now() - 1000 * 60 * 45), // 45 phút trước
    items: [
      {
        productName: 'Pizza Xúc Xích Ý (Pepperoni)',
        variantName: 'Size Vừa 25cm',
        ingredientNames: ['Ớt Jalapeno cay'],
        quantity: 1,
      },
      {
        productName: 'Khoai tây nướng lò với sốt',
        quantity: 1,
      },
    ],
  },
  {
    orderNumber: 'FF-948120-3371',
    status: 'PENDING',
    paymentStatus: 'PENDING',
    paymentMethod: 'COD',
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    guestName: 'Nguyễn Văn Kiên',
    guestPhone: '0987654321',
    guestAddress: 'Số 12 ngõ 58 Trương Định, Tương Mai, Hoàng Mai, Hà Nội',
    notes: 'Giao nhanh giúp mình với',
    deliveryFee: 15000,
    discount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 5), // 5 phút trước
    items: [
      {
        productName: 'Pizza 4 Loại Thịt',
        variantName: 'Size Lớn 30cm',
        ingredientNames: ['Phô mai Cheddar', 'Thịt viên'],
        quantity: 1,
      },
      {
        productName: 'Dodster cay',
        quantity: 1,
      },
    ],
  },
  {
    orderNumber: 'FF-219401-4491',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'ONLINE',
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    guestName: 'Nguyễn Văn Kiên',
    guestPhone: '0987654321',
    guestAddress: 'Số 12 ngõ 58 Trương Định, Tương Mai, Hoàng Mai, Hà Nội',
    notes: 'Bỏ ít đá vào nước',
    deliveryFee: 15000,
    discount: 30000,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24), // 1 ngày trước
    items: [
      {
        productName: 'Pizza Hải Sản Truyền Thống',
        variantName: 'Size Vừa 25cm',
        ingredientNames: ['Viền phô mai'],
        quantity: 1,
      },
      {
        productName: 'Mì Ý Hải Sản Sốt Pesto',
        quantity: 1,
      },
      {
        productName: 'Sữa lắc chuối',
        quantity: 1,
      },
    ],
  },
  {
    orderNumber: 'FF-104928-6623',
    status: 'CANCELLED',
    paymentStatus: 'CANCELLED',
    paymentMethod: 'COD',
    userEmail: 'nguyenvankien2004hanam@gmail.com',
    guestName: 'Nguyễn Văn Kiên',
    guestPhone: '0987654321',
    guestAddress: 'Số 12 ngõ 58 Trương Định, Tương Mai, Hoàng Mai, Hà Nội',
    notes: '',
    deliveryFee: 15000,
    discount: 0,
    cancelReason: 'Tôi muốn đổi món / đổi địa chỉ nhận hàng',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72), // 3 ngày trước
    items: [
      {
        productName: 'Pizza 4 Cheese',
        variantName: 'Size Nhỏ 20cm',
        quantity: 1,
      },
      {
        productName: 'Cappuccino caramen',
        quantity: 1,
      },
    ],
  },
];

// Example Reviews
export const reviews = [
  {
    userId: 1,
    productId: 1,
    orderId: 1,
    rating: 5,
    comment: 'Delicious pizza!',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
